flowchart TD
  cTestComponent["TestComponent<br/>TestComponent"]
  m_cTestComponent_Start["Start()<br/>Return: System.Void"]
  cTestComponent --> m_cTestComponent_Start
  s_m_cTestComponent_Start_0["Expression"]
  m_cTestComponent_Start --> s_m_cTestComponent_Start_0
  expr_s_m_cTestComponent_Start_0_0{" Assignment<br/>Vector3 "}
  s_m_cTestComponent_Start_0 --> expr_s_m_cTestComponent_Start_0_0
  expr_child_expr_s_m_cTestComponent_Start_0_0_0{" MemberAccess<br/>Type: Vector3<br/>Property: position "}
  expr_s_m_cTestComponent_Start_0_0 --> expr_child_expr_s_m_cTestComponent_Start_0_0_0
  expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_0_0{" Identifier<br/>Type: Transform<br/>Value: transform "}
  expr_child_expr_s_m_cTestComponent_Start_0_0_0 --> expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_0_0
  expr_child_expr_s_m_cTestComponent_Start_0_0_1{" ObjectCreation<br/>Type: Vector3 "}
  expr_s_m_cTestComponent_Start_0_0 --> expr_child_expr_s_m_cTestComponent_Start_0_0_1
  expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_1_0{" Literal<br/>Type: Int32<br/>Value: 0 "}
  expr_child_expr_s_m_cTestComponent_Start_0_0_1 --> expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_1_0
  expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_1_1{" Literal<br/>Type: Int32<br/>Value: 0 "}
  expr_child_expr_s_m_cTestComponent_Start_0_0_1 --> expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_1_1
  expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_1_2{" Literal<br/>Type: Int32<br/>Value: 0 "}
  expr_child_expr_s_m_cTestComponent_Start_0_0_1 --> expr_child_expr_child_expr_s_m_cTestComponent_Start_0_0_1_2
  m_cTestComponent_Update["Update()<br/>Return: System.Void"]
  cTestComponent --> m_cTestComponent_Update
  s_m_cTestComponent_Update_0["Expression"]
  m_cTestComponent_Update --> s_m_cTestComponent_Update_0
  expr_s_m_cTestComponent_Update_0_0{" MethodInvocation<br/>Void "}
  s_m_cTestComponent_Update_0 --> expr_s_m_cTestComponent_Update_0_0
  expr_child_expr_s_m_cTestComponent_Update_0_0_0{" Identifier<br/>Type: Transform<br/>Value: transform "}
  expr_s_m_cTestComponent_Update_0_0 --> expr_child_expr_s_m_cTestComponent_Update_0_0_0
  expr_child_expr_s_m_cTestComponent_Update_0_0_1{" ObjectCreation<br/>Type: Vector3 "}
  expr_s_m_cTestComponent_Update_0_0 --> expr_child_expr_s_m_cTestComponent_Update_0_0_1
  expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_0{" Literal<br/>Type: Int32<br/>Value: 0 "}
  expr_child_expr_s_m_cTestComponent_Update_0_0_1 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_0
  expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1{" Binary<br/>Type: Single<br/>Op: * "}
  expr_child_expr_s_m_cTestComponent_Update_0_0_1 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1
  expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_0{" MemberAccess<br/>Type: Single<br/>Property: deltaTime "}
  expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1 --> expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_0
  expr_child_expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_0_0{" Identifier<br/>Type: Time<br/>Value: Time "}
  expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_0 --> expr_child_expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_0_0
  expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_1{" Identifier<br/>Type: Single<br/>Value: speed "}
  expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1 --> expr_child_expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_1_1
  expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_2{" Literal<br/>Type: Int32<br/>Value: 0 "}
  expr_child_expr_s_m_cTestComponent_Update_0_0_1 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_0_0_1_2
  s_m_cTestComponent_Update_1["For"]
  s_m_cTestComponent_Update_0 --> s_m_cTestComponent_Update_1
  expr_s_m_cTestComponent_Update_1_0{" ForInitializer<br/>Int32 "}
  s_m_cTestComponent_Update_1 --> expr_s_m_cTestComponent_Update_1_0
  expr_child_expr_s_m_cTestComponent_Update_1_0_0{" Assignment "}
  expr_s_m_cTestComponent_Update_1_0 --> expr_child_expr_s_m_cTestComponent_Update_1_0_0
  expr_child_expr_child_expr_s_m_cTestComponent_Update_1_0_0_0{" Identifier<br/>Type: Int32<br/>Value: i "}
  expr_child_expr_s_m_cTestComponent_Update_1_0_0 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_1_0_0_0
  expr_child_expr_child_expr_s_m_cTestComponent_Update_1_0_0_1{" Literal<br/>Type: Int32<br/>Value: 0 "}
  expr_child_expr_s_m_cTestComponent_Update_1_0_0 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_1_0_0_1
  expr_s_m_cTestComponent_Update_1_1{" ForCondition<br/>Boolean "}
  s_m_cTestComponent_Update_1 --> expr_s_m_cTestComponent_Update_1_1
  expr_child_expr_s_m_cTestComponent_Update_1_1_0{" Binary<br/>Type: Boolean<br/>Op: < "}
  expr_s_m_cTestComponent_Update_1_1 --> expr_child_expr_s_m_cTestComponent_Update_1_1_0
  expr_child_expr_child_expr_s_m_cTestComponent_Update_1_1_0_0{" Identifier<br/>Type: Int32<br/>Value: i "}
  expr_child_expr_s_m_cTestComponent_Update_1_1_0 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_1_1_0_0
  expr_child_expr_child_expr_s_m_cTestComponent_Update_1_1_0_1{" Literal<br/>Type: Int32<br/>Value: 10 "}
  expr_child_expr_s_m_cTestComponent_Update_1_1_0 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_1_1_0_1
  expr_s_m_cTestComponent_Update_1_2{" ForIncrementor<br/>Int32 "}
  s_m_cTestComponent_Update_1 --> expr_s_m_cTestComponent_Update_1_2
  expr_child_expr_s_m_cTestComponent_Update_1_2_0{" PostfixUnary<br/>Type: Int32<br/>Op: ++ "}
  expr_s_m_cTestComponent_Update_1_2 --> expr_child_expr_s_m_cTestComponent_Update_1_2_0
  expr_child_expr_child_expr_s_m_cTestComponent_Update_1_2_0_0{" Identifier<br/>Type: Int32<br/>Value: i "}
  expr_child_expr_s_m_cTestComponent_Update_1_2_0 --> expr_child_expr_child_expr_s_m_cTestComponent_Update_1_2_0_0
  child_s_m_cTestComponent_Update_1_0["Expression"]
  s_m_cTestComponent_Update_1 --> child_s_m_cTestComponent_Update_1_0
  expr_child_s_m_cTestComponent_Update_1_0_0{" Assignment<br/>Vector3 "}
  child_s_m_cTestComponent_Update_1_0 --> expr_child_s_m_cTestComponent_Update_1_0_0
  expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_0{" MemberAccess<br/>Type: Vector3<br/>Property: position "}
  expr_child_s_m_cTestComponent_Update_1_0_0 --> expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_0
  expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_0_0{" Identifier<br/>Type: Transform<br/>Value: transform "}
  expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_0 --> expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_0_0
  expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1{" MethodInvocation<br/>Type: Vector3<br/>Method: TransformDirection() "}
  expr_child_s_m_cTestComponent_Update_1_0_0 --> expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1
  expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_0{" Identifier<br/>Type: Transform<br/>Value: transform "}
  expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1 --> expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_0
  expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1{" Binary<br/>Type: Vector3<br/>Op: * "}
  expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1 --> expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1
  expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0{" Binary<br/>Type: Vector3<br/>Op: * "}
  expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1 --> expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0
  expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_0{" MemberAccess<br/>Type: Vector3<br/>Property: forward "}
  expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0 --> expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_0
  expr_child_expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_0_0{" Identifier<br/>Type: Vector3<br/>Value: Vector3 "}
  expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_0 --> expr_child_expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_0_0
  expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_1{" MemberAccess<br/>Type: Single<br/>Property: deltaTime "}
  expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0 --> expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_1
  expr_child_expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_1_0{" Identifier<br/>Type: Time<br/>Value: Time "}
  expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_1 --> expr_child_expr_child_expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_0_1_0
  expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_1{" Identifier<br/>Type: Single<br/>Value: speed "}
  expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1 --> expr_child_expr_child_expr_child_expr_child_s_m_cTestComponent_Update_1_0_0_1_1_1
