#if UNITY_EDITOR && HAVE_VISUAL_SCRIPTING
// TODO make runtime capable

using UnityEngine;
using UnityGLTF.Interactivity;
using UnityGLTF.Interactivity.Export;
using UnityGLTF.Interactivity.Schema;

public class InterfaceSample : MonoBehaviour ,IInteractivityExport
{
    public void OnInteractivityExport(GltfInteractivityExportNodes nodes)
    {

        var addNode = nodes.CreateNode<Math_AddNode>();
        addNode.SetValueInSocket("a", 1);
        addNode.SetValueInSocket("b", 2);
        addNode.OutputValueSocket["value"].expectedType = ExpectedType.Int;

        //Get generic auto generated Schema: GenericUnitExport.GetAutoGeneratedSchema("math/sub")
        
        var equalNode = nodes.CreateNode<Math_EqNode>();
        equalNode.SetValueInSocket("a", 1);
        equalNode.SetValueInSocketSource("b", addNode, "value");
        
        var vector3Node = nodes.CreateNode<Math_Combine3Node>();
        vector3Node.SetValueInSocket("a", 0f);
        vector3Node.SetValueInSocket("b", 0f);
        vector3Node.SetValueInSocketSource("c", equalNode, "value", TypeRestriction.LimitToFloat);
        
        var setPositionNode = nodes.CreateNode<Pointer_SetNode>();
        PointersHelper.AddPointerConfig(setPositionNode, "/nodes/{" + PointersHelper.IdPointerNodeIndex + "}/translation", GltfTypes.Float3);
        int thisTransformIndex = nodes.Context.exporter.GetTransformIndex(transform);
        PointersHelper.AddPointerTemplateValueInput(setPositionNode, PointersHelper.IdPointerNodeIndex, thisTransformIndex);
        setPositionNode.SetValueInSocketSource("value", vector3Node, "value", TypeRestriction.LimitToFloat3);
        
        var startNode = nodes.CreateNode<Event_OnStartNode>();
        startNode.SetFlowOut(Event_OnStartNode.IdFlowOut, setPositionNode, Pointer_SetNode.IdFlowIn);
       
    }
}

#endif